services:
  postgres:
    image: postgres:17
    container_name: postgres-wattcast
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init_db_postgres.sql:ro
      - ./airflow/init_db_airflow.sql:/docker-entrypoint-initdb.d/init_db_airflow.sql:ro
    restart: unless-stopped
    mem_limit: 512m

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-wattcast
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    mem_limit: 350m

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-wattcast
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    mem_limit: 512m

  init-buckets:
    image: quay.io/minio/mc:latest
    container_name: init_bucket_minio
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " until /usr/bin/mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        echo 'En attente de MinIO...';
        sleep 1;
      done; /usr/bin/mc mb local/bucket-silver --ignore-existing; /usr/bin/mc mb local/bucket-bronze --ignore-existing; exit 0; "
    mem_limit: 256m

volumes:
  minio_data:
  postgres_data:
  pgadmin_data:

networks:
  default:
    name: wattcast
    external: true
