services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka-wattcast
    ports:
      - "9094:9094"
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_HEAP_OPTS: "-Xmx384m -Xms384m"
    mem_limit: 768m
    restart: unless-stopped

  jobmanager:
    build:
      context: ./flink
      dockerfile: Dockerfile
    image: wattcast-pyflink:1.19
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ../src:/opt/flink/src:ro
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 600m
    mem_limit: 750m
    restart: unless-stopped

  taskmanager:
    build:
      context: ./flink
      dockerfile: Dockerfile
    image: wattcast-pyflink:1.19
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ../src:/opt/flink/src:ro
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 1
        taskmanager.memory.process.size: 800m
    mem_limit: 1000m
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-wattcast
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command:
      redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-changeit}
    restart: unless-stopped
    mem_limit: 256m

volumes:
  redis_data:

networks:
  default:
    name: wattcast
    external: true
